module.exports = {
    calendarRewards: {
        1: { item: "Candy Cane", amount: 1 },
        2: { item: "Hot Chocolate", amount: 1 },
        3: { item: "Snowball", amount: 5 },
        4: { item: "Christmas Hat", amount: 1 },
        5: { item: "Fireworks", amount: 2 },
        6: { item: "Christmas Cookie", amount: 3 },
        7: { item: "Santa Suit", amount: 1 },
        8: { item: "Holiday Lights", amount: 1 },
        9: { item: "Gift Box", amount: 1 },
        10: { item: "Gingerbread Man", amount: 2 },
        11: { item: "Elf Hat", amount: 1 },
        12: { item: "Christmas Tree", amount: 1 },
        13: { item: "Snowman Kit", amount: 1 },
        14: { item: "Present", amount: 1 },
        15: { item: "Holiday Sweater", amount: 1 },
        16: { item: "Candy Cane", amount: 1 },
        17: { item: "Mistletoe", amount: 1 },
        18: { item: "Gift Wrap", amount: 1 },
        19: { item: "Chocolate Bar", amount: 3 },
        20: { item: "Reindeer Antlers", amount: 1 },
        21: { item: "Holiday Socks", amount: 1 },
        22: { item: "Snowball", amount: 10 },
        23: { item: "Christmas Ornament", amount: 1 },
        24: { item: "Golden Star", amount: 1 },
    },
};
